apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
  creationTimestamp: "2025-09-04T10:42:18Z"
  generation: 1
  name: amdgpu-device-plugin-daemonset
  namespace: kube-system
  resourceVersion: "847"
  uid: 99dac911-d815-4c18-9df5-cf1500b33c3f
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: amdgpu-dp-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: amdgpu-dp-ds
    spec:
      containers:
      - image: rocm/k8s-device-plugin
        imagePullPolicy: Always
        name: amdgpu-dp-cntr
        resources: {}
        securityContext:
          capabilities:
            drop:
            - ALL
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kubelet/device-plugins
          name: dp
        - mountPath: /sys
          name: sys
        - name: dev-kfd
          mountPath: /dev/kfd
        - name: dev-dri
          mountPath: /dev/dri
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/arch: amd64
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/kubelet/device-plugins
          type: ""
        name: dp
      - hostPath:
          path: /sys
          type: ""
        name: sys
      - name: dev-kfd
        hostPath:
          path: /dev/kfd
      - name: dev-dri
        hostPath:
          path: /dev/dri
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
  observedGeneration: 1
